### ISSUE TITLE
Adding /status Endpoint For Uptime Monitors to Pickup

### ISSUE THREAD

**Issue by icxven** [syeopite/priviblur#13]
as priviblur is making requests to tumblr in the main page. uptime monitors are getting lots of errors. so /status endpoint without any outbound requests would be great.

**Comment by syeopite** [comment]
Just checking for whether or not a service is up instead of whether or not it's working seems moot to me.

If Priviblur experiences an error on the main page — most likely #4 — then the rest of the site is likely also broken.

**Comment by icxven** [comment]
valid point.
