### ISSUE TITLE
Add ability to open images in new tab with ctrl-click

### ISSUE THREAD

**Issue by the-blank-x** [syeopite/priviblur#15]
When viewing images ([example if you want](https://pb.bloat.cat/brooke2valley/737605911853613056/it-just-couldnt-stay-warm-could-it-collab)), I'd like to be able to ctrl+click to open an image in a new tab

(Unsure if this goes here or in https://github.com/syeopite/npf-renderer)

**Comment by syeopite** [comment]
Sounds good to me, though I think I'll personally prefer having the click-to-maximize image functionality seen on Tumblr though.

I'll have to see if they can both be implemented

**Comment by the-blank-x** [comment]
Mind if I make a PR to implement this (without the click-to-maximize 
functionality)?

**Comment by syeopite** [comment]
Yeah go ahead! This should be implemented on Priviblur's side though, as it's a bit out of scope for npf-renderer. 

There's a subclassed formatter here if you need to modify npf-renderer's behavior https://github.com/syeopite/priviblur/blob/master/src/helpers/ext_npf_renderer.py

**Comment by the-blank-x** [comment]
Thanks for the link! I've managed to get it working, but now some images are only 6px tall. Take welldrawnfish/740618359551459328 for example:

Before:
![](https://github.com/syeopite/priviblur/assets/45762106/7f4f574c-5ffb-4bea-8f11-e0bc60f67edc)

After:
![](https://github.com/syeopite/priviblur/assets/45762106/14f62a2a-ff52-42a7-a0d2-61b915bde1dd)

I've also reproduced this for deadeyedfae/742383892563181568 and deadeyedfae/742211931260289024, but not deadeyedfae/742238963432046592. For reference, here's my patch:
```patch
diff --git a/src/helpers/ext_npf_renderer.py b/src/helpers/ext_npf_renderer.py
index 34d0f29..5d5c76e 100644
--- a/src/helpers/ext_npf_renderer.py
+++ b/src/helpers/ext_npf_renderer.py
@@ -110,6 +110,14 @@ class NPFFormatter(npf_renderer.format.Formatter):
         self.blog_name = blog_name
         self.post_id = post_id
 
+    def _linkify_images(self, element):
+        if isinstance(element, dominate.tags.img):
+            return dominate.tags.a(element, href=element.src)
+
+        for index, child in enumerate(element):
+            element[index] = self._linkify_images(child)
+        return element
+
     def _format_poll(self, block):
         poll_html = super()._format_poll(block)
         poll_html["data-poll-id"] = block.poll_id
@@ -132,6 +140,10 @@ class NPFFormatter(npf_renderer.format.Formatter):
 
         return poll_html
 
+    def _format_image(self, block, row_length=1, override_padding=1):
+        image_html = super()._format_image(block, row_length, override_padding)
+        return self._linkify_images(image_html)
+
 
 async def format_npf(contents, layouts=None, blog_name=None, post_id=None,*, poll_callback=None):
     """Wrapper around npf_renderer.format_npf for extra functionalities
```

**Comment by syeopite** [comment]
`override_padding` should be set to None by default instead of 1. By setting it to one you are forcing a specific aspect ratio into every single image that doesn't have layout data attached to it, hence the 6px tall images.

**Comment by the-blank-x** [comment]
Whoops lol

I might not be able to test this within the next two days
