### ISSUE TITLE
Post caption overlaps with text

### ISSUE THREAD

**Issue by the-blank-x** [syeopite/priviblur#16]
https://priviblur.zangetsu.kaizoku.cyou/devogamer/612972148753088512/the-brave-knight-belongs-to-yugogeer012

![](https://github.com/syeopite/priviblur/assets/45762106/7d52d698-4ee0-4b4e-9bc2-de40b1f70c68)

**Comment by syeopite** [comment]
This will be fixed by #9 once the next version of npf-renderer gets released

![0 12 0](https://github.com/syeopite/priviblur/assets/70992037/2bf7356b-7405-4478-bbe7-59cefc0d895f)
