### ISSUE TITLE
Suggestion: Use /post as part of the resolve URL

### ISSUE THREAD

**Issue by thefranke** [syeopite/priviblur#19]
Hey there, exciting project, thanks for making it!

In order to make forwarding more easy, I have a suggestion. 

The canonical URL for a post on Tumblr is:
`https://USERPAGE.tumblr.com/post/POSTNUMBER/POSTTITLE`

Whereas on Priviblur it is:
`https://INSTANCE/USERPAGE/POSTNUMBER/TITLE`

Instead, it would be simpler if the canonical address would be the same on Priviblur, like this:
`https://INSTANCE/USERPAGE/post/POSTNUMBER/TITLE`

That way, one doesn't need two expressions to forward a Tumblr blog via a Redirector, but only a simple catchall asterisk expression such as

`*.tumblr.com/*` -> `https://INSTANCE/$1/$2`

**Comment by syeopite** [comment]
Great idea!

I've added redirects for the `<blog>/post/*` endpoints but I won't be making it the canonical URL. 

The current routing scheme is designed to match with Tumblr's "blog view" feature which follows the scheme of `www.tumblr.com/<blog>/*` without the extra `/post/` segmeng

**Comment by thefranke** [comment]
Oh I see, that makes sense. Thanks for the extra route!

**Comment by thefranke** [comment]
> Got it with this include pattern: `https:\/\/(.+)\.tumblr\.com\/(.*)`. Testing...

Excellent, sorry for seeing this message so late.
