### ISSUE TITLE
Dark theme support?

### ISSUE THREAD

**Issue by ThunderHen** [syeopite/priviblur#22]
I would like to have Dark theme support.
really cool project. Thanks for making it.

**Comment by syeopite** [comment]
Yeah dark mode would be great. It's already in the works! See #10. If all goes well it should be included in the 0.2.0 release

**Comment by syeopite** [comment]
A dark mode has been added in #35 which brings the theme along with a whole host of other UI changes. 

![Dark mode screenshot](https://github.com/syeopite/priviblur/assets/70992037/867f3689-ca1c-49ab-9060-4d6728fc0528)


The PR has reached a state where I am mostly satisfied with everything, and it should get merged soon. Feel free to pull changes from that PR. 

In the meantime any feedback would be greatly appreciated!

**Comment by KaKi87** [comment]
> any feedback would be greatly appreciated!

Looks nice on this page, will provide further comments if you'd screenshot other pages, unless this feature is already available on an instance !

**Comment by syeopite** [comment]
Of course! I don't believe any instance has deployed it yet so here's a couple other pages

![asks and a dropdown menu](https://github.com/syeopite/priviblur/assets/70992037/4cc928c9-fdde-4e08-b636-cad2e58e4f02)
![blog](https://github.com/syeopite/priviblur/assets/70992037/9d573046-aa96-4e25-bf4a-978f4255101b)

![polls](https://github.com/syeopite/priviblur/assets/70992037/b7220090-474e-49f4-bec7-d79bf057533c)

**Comment by KaKi87** [comment]
This is readable, with perfect contrasts, I'm looking forward to see it deployed !
