### ISSUE TITLE
/<blog>/search/<query> not implemented

### ISSUE THREAD

**Issue by the-blank-x** [syeopite/priviblur#25]
Example Tumblr URLs: https://www.tumblr.com/kaylasartwork/search/wear%20more%20black and https://mezzyb0nb0n.tumblr.com/search/wear%20more%20black
Example Priviblur URL: https://priviblur.zangetsu.kaizoku.cyou/kaylasartwork/search/wear%20more%20black

![](https://github.com/syeopite/priviblur/assets/45762106/2819013b-92e2-45b2-a563-62c369053d52)
![](https://github.com/syeopite/priviblur/assets/45762106/c6b0c783-9c60-4c91-a17d-0b4a0d4dd46f)
![](https://github.com/syeopite/priviblur/assets/45762106/1db0becc-813c-4576-b95f-d2d21855b109)

**Comment by syeopite** [comment]
And there we go, implemented.
