### ISSUE TITLE
Unsupported video format - NPF content block

### ISSUE THREAD

**Issue by myntfarm** [syeopite/priviblur#33]
![image](https://github.com/syeopite/priviblur/assets/96462665/64921d79-051c-46eb-a909-3a9bb3acb4c5)
Unsupported content placeholder
Hello! I'm a placeholder for the unsupported "video" type NPF content block. Please report me!

**Comment by syeopite** [comment]
It looks like you're using an outdated version of Priviblur. 

Support for video blocks was added a couple weeks ago.
