### ISSUE TITLE
[fr] support for direct image links

### ISSUE THREAD

**Issue by throwaway26425** [syeopite/priviblur#42]
hi, I was wondering if there were any plans to add support for these type of URLs?

https://68.media.tumblr.com/314312f04c733ea25f4ca72015bef08a/tumblr_ofeqgbPc3Q1r45099o1_500.jpg

https://66.media.tumblr.com/5af9b0bad5f55ec8a75cb86aa916e61f/tumblr_mqnnr6m4QP1ra9owho1_500.png

**Comment by syeopite** [comment]
Hello! Direct image links already supported by Priviblur.

You just have to structure them a little bit differently. In the cases of your two examples above,

https://priviblur.pussthecat.org/tblr/media/68/314312f04c733ea25f4ca72015bef08a/tumblr_ofeqgbPc3Q1r45099o1_500.jpg

And 

https://priviblur.pussthecat.org/tblr/media/66/5af9b0bad5f55ec8a75cb86aa916e61f/tumblr_mqnnr6m4QP1ra9owho1_500.png
